project:
  name: Weak Raider
  port: 8080
  debug: true
  environment: development

database:
  sslmode: disable
  migrations: migrations
  driver: pgx
  connections:
    maxOpenCons: 5
    maxIdleCons: 5
    connMaxIdleTime: 5m
    connMaxLifeTime: 5m