services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "$WR_PG_NAME", "-U", "$WR_PG_USER" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $WR_PG_USER
      POSTGRES_PASSWORD: $WR_PG_PASS
      POSTGRES_DB: $WR_PG_NAME
    networks:
      - wrnw
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
    driver: local


networks:
  wrnw:
    driver: bridge