openapi: "3.0.0"
info:
  version: 1.0.0
  title: Blizzard API
servers:
  - url: https://eu.api.blizzard.com
  - url: https://oauth.battle.net
paths:
  /token:
    post:
      operationId: authorize
      parameters:
        - $ref: '#/components/parameters/Authorization'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthTokenResponse"
          description: Successful login
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthTokenRequest'

  /data/wow/journal-expansion/index?locale=en_US:
    get:
      operationId: journalExpansionIndex
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/Namespace'
      responses:
        '200':
          description: Успешный ответ.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JEIndexResponse'

  /data/wow/journal-instance/{instance_id}:
    get:
      operationId: journalInstance
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/Namespace'
        - $ref: '#/components/parameters/InstanceId'
      responses:
        '200':
          description: Успешный ответ.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JEInstanceResponse'

  /data/wow/journal-expansion/{expansion_id}:
    get:
      operationId: journalExpansionById
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/Namespace'
        - $ref: '#/components/parameters/ExpansionId'
      responses:
        '200':
          description: Успешный ответ.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EJSeasonResponse'

  /profile/wow/character/{realm}/{character}/equipment?locale=en_US:
    get:
      operationId: equipment
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/Namespace'
        - $ref: '#/components/parameters/Realm'
        - $ref: '#/components/parameters/Character'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileEquipmentResponse'
          description: Players equipment

components:
  parameters:
    Authorization:
      name: Authorization
      description: blizzard auth header
      required: true
      schema:
        type: string
      in: header
    Namespace:
      name: Battlenet-Namespace
      description: Namespace.
      required: true
      schema:
        type: string
        enum:
          - static-eu
          - profile-eu
          - dynamic-eu
      in: header
    Realm:
      name: realm
      description: Realm to query
      required: true
      schema:
        type: string
      in: path
    Character:
      name: character
      description: Character to query
      required: true
      schema:
        type: string
      in: path
    ExpansionId:
      name: expansion_id
      description: Идентификатор дополнения
      required: true
      schema:
        type: string
      in: path
    InstanceId:
      name: instance_id
      description: Идентификатор подземелья
      required: true
      schema:
        type: string
      in: path

  schemas:
    AuthTokenRequest:
      type: object
      required:
        - grant_type
      properties:
        grant_type:
          type: string
          description: Required grant
          default: 'client_credentials'

    AuthTokenResponse:
      type: object
      required: 
        - access_token
      properties:
        access_token:
          type: string
          description: Access Token for future use.

    ProfileEquipmentResponse:
      type: object
      required:
        - equipped_items
      properties:
        equipped_items:
          type: array
          description: List of equipped by player items.
          items:
            $ref: '#/components/schemas/ProfileEquipmentItem'

    ProfileEquipmentItem:
      type: object
      required:
        - item
        - slot
      properties:
        item:
          type: object
          description: Information about item
          required:
            - id
          properties:
            id:
              type: integer
              description: Item ID
        bonus_list:
          type: array
          description: Bonus ID used in simc
          items:
            type: integer
            description: Bonus ID
        slot:
          type: object
          required:
            - type
          properties:
            type:
              type: string
              description: Uppercased item slot
        name:
          type: string
          description: In-game item's name
        stats:
          type: array
          description: Item stats.
          items:
            type: object
            required:
              - type
              - value
            properties:
              type:
                type: string
                description: Uppercased stat name
              value:
                type: integer
                description: Value that item grants to player
              is_negated:
                type: boolean
                description: Is obsolete stat to character
        sockets:
          type: array
          description: Item's sockets
          items:
            type: object
            properties:
              item:
                type: object
                description: Item socketed in socket
                required:
                  - id
                  - name
                properties:
                  id:
                    type: integer
                    description: Socketed item id
                  name:
                    type: string
                    description: Socketed item name
        enchantments:
          type: array
          items:
            type: object
            description: enchantment info
            required:
              - display_string
              - enchantment_id
            properties:
              display_string:
                type: string
                description: In-game name
              enchantment_id:
                type: integer
                description: Internal ID

    Translation:
      type: object
      additionalProperties:
        type: string


    JEInstanceResponse:
      type: object
      required:
        - name
        - encounters
      properties:
        name:
          $ref: "#/components/schemas/Translation"
        encounters:
          type: array
          items:
            $ref: '#/components/schemas/JEInstanceEncounter'

    JEInstanceEncounter:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          description: Идентификатор босса подземелья.
        name:
          $ref: '#/components/schemas/Translation'

    JEIndexResponse:
      type: object
      required:
        - tiers
      properties:
        tiers:
          type: array
          description: Список дополнений
          items:
            type: object
            required:
              - name
              - id
            properties:
              name:
                type: string
                description: Название дополнения
                example: Cataclysm
              id:
                type: integer
                description: Идентификатор дополнения

    EJSeasonInstance:
      type: array
      items:
        type: object
        required:
          - name
          - id
        properties:
          name:
            $ref: '#/components/schemas/Translation'
          id:
            type: integer
            description: Идентификатор рейда

    EJSeasonResponse:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          description: Идентификатор дополнения
        name:
          $ref: '#/components/schemas/Translation'
        dungeons:
          $ref: '#/components/schemas/EJSeasonInstance'
        raids:
          $ref: '#/components/schemas/EJSeasonInstance'
