openapi: 3.0.0
info:
  title: Generated API
  version: 1.0.0
servers:
  - url: https://www.warcraftlogs.com
  - url: https://www.warcraftlogs.com/api/v2/client
paths:
  /oauth/token:
    post:
      operationId: authorize
      parameters:
        - $ref: '#/components/parameters/Authorization'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenResponse'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthTokenRequest'

components:
  parameters:
    Authorization:
      name: Authorization
      description: warcraftlogs auth header http auth
      required: true
      schema:
        type: string
      in: header

  schemas:
    AuthTokenRequest:
      type: object
      required:
        - grant_type
      properties:
        grant_type:
          type: string
          description: Required grant
          default: 'client_credentials'

    AuthTokenResponse:
      type: object
      required:
        - token_type
        - expires_in
        - access_token
      properties:
        token_type:
          type: string
          example: Bearer
        expires_in:
          type: integer
          description: Seconds to expire.
        access_token:
          type: string
