openapi: 3.0.0
info:
  title: Generated API
  version: 1.0.0
servers:
  - url: https://www.warcraftlogs.com
paths:
  /oauth/token:
    post:
      operationId: authorize
      parameters:
        - $ref: '#/components/parameters/Authorization'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenResponse'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthTokenRequest'

  /api/v2/client:
    post:
      operationId: graphql
      parameters:
        - $ref: '#/components/parameters/Authorization'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GraphQlResponse'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GraphQlRequest'

components:
  parameters:
    Authorization:
      name: Authorization
      description: warcraftlogs auth header (http auth / bearer)
      required: true
      schema:
        type: string
      in: header

  schemas:
    AuthTokenRequest:
      type: object
      required:
        - grant_type
      properties:
        grant_type:
          type: string
          description: Required grant
          default: 'client_credentials'

    AuthTokenResponse:
      type: object
      required:
        - token_type
        - expires_in
        - access_token
      properties:
        token_type:
          type: string
          example: Bearer
        expires_in:
          type: integer
          description: Seconds to expire.
        access_token:
          type: string

    GraphQlRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: GraphQL query

    GraphQlResponse:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - reportData
          properties:
            reportData:
              type: object
              required:
                - reports
              properties:
                reports:
                  type: object
                  required:
                    - data
                  properties:
                    data:
                      type: array
                      items:
                        type: object
                        required:
                          - code
                          - title
                          - startTime
                          - endTime
                          - zone
                        properties:
                          code:
                            type: string
                            description: WarcraftLogs report code.
                            example: fb9AcBJGvNPMwTtd
                          title:
                            type: string
                            description: Report name
                            example: Убиваем ласта
                          startTime:
                            type: integer
                            description: UnixTimestamp of report start
                          endTime:
                            type: integer
                            description: UnixTimestamp of report end
                          zone:
                            type: object
                            required:
                              - id
                              - name
                            properties:
                              id:
                                type: integer
                                description: Zone ID
                              name:
                                type: string
                                description: Zone name
                                example: VS / DR / MQD
