openapi: "3.0.0"
info:
  version: 1.0.0
  title: wowaudit API
servers:
  - url: https://wowaudit.com
paths:
  /v1/characters:
    get:
      operationId: getCharacters
      parameters:
        - $ref: "#/components/parameters/Authorization"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CharactersResponse"
          description: Successful response

  /v1/period:
    get:
      operationId: getPeriod
      parameters:
        - $ref: "#/components/parameters/Authorization"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PeriodResponse"
          description: Successful response

components:
  parameters:
    Authorization:
      name: Authorization
      description: wowaudit auth header
      required: true
      schema:
        type: string
      in: header

  schemas:
    CharactersResponse:
      type: array
      items:
        $ref: '#/components/schemas/Character'

    PeriodResponse:
      type: object
      required:
        - current_season
      properties:
        current_season:
          type: object
          required:
            - id
            - name
          properties:
            id:
              type: integer
              description: ID сезона в wow audit
            name:
              type: string
              description: Название сезона в wow audit

    Character:
      type: object
      required:
        - name
        - realm
        - class
        - rank
        - role
        - note
        - blizzard_id
      properties:
        name:
          type: string
          description: Character name
        realm:
          type: string
          description: Character's realms
        class:
          type: string
          description: Class name
        rank:
          type: string
          description: Rank in wowaudit
        role:
          type: string
          description: Player role in raid
        note:
          type: string
          nullable: true
          description: Note on player in wowaudit
        blizzard_id:
          type: integer
          description: Blizzard API ID.
